// Code generated by protoc-gen-go.
// source: sampleone2.proto
// DO NOT EDIT!

/*
Package xlsx2pb is a generated protocol buffer package.

It is generated from these files:
	sampleone2.proto

It has these top-level messages:
	SAMPLEONE
	SAMPLEONE_ARRAY
*/
package xlsx2pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type SAMPLEONE struct {
	// Comment1
	SampleID *uint64 `protobuf:"varint,2,req" json:"SampleID,omitempty"`
	// Comment2
	Times *int64 `protobuf:"varint,3,opt" json:"Times,omitempty"`
	// Comment3
	NameID           *string                 `protobuf:"bytes,4,opt" json:"NameID,omitempty"`
	StructName       []*SAMPLEONE_StructName `protobuf:"bytes,5,rep,name=structName" json:"structName,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SAMPLEONE) Reset()         { *m = SAMPLEONE{} }
func (m *SAMPLEONE) String() string { return proto.CompactTextString(m) }
func (*SAMPLEONE) ProtoMessage()    {}

func (m *SAMPLEONE) GetSampleID() uint64 {
	if m != nil && m.SampleID != nil {
		return *m.SampleID
	}
	return 0
}

func (m *SAMPLEONE) GetTimes() int64 {
	if m != nil && m.Times != nil {
		return *m.Times
	}
	return 0
}

func (m *SAMPLEONE) GetNameID() string {
	if m != nil && m.NameID != nil {
		return *m.NameID
	}
	return ""
}

func (m *SAMPLEONE) GetStructName() []*SAMPLEONE_StructName {
	if m != nil {
		return m.StructName
	}
	return nil
}

type SAMPLEONE_StructName struct {
	// Comment4
	RewardID *string `protobuf:"bytes,1,opt" json:"RewardID,omitempty"`
	// Comment5
	Count *uint32 `protobuf:"varint,2,opt" json:"Count,omitempty"`
	// Comment6
	Weight           *float64 `protobuf:"fixed64,3,opt" json:"Weight,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SAMPLEONE_StructName) Reset()         { *m = SAMPLEONE_StructName{} }
func (m *SAMPLEONE_StructName) String() string { return proto.CompactTextString(m) }
func (*SAMPLEONE_StructName) ProtoMessage()    {}

func (m *SAMPLEONE_StructName) GetRewardID() string {
	if m != nil && m.RewardID != nil {
		return *m.RewardID
	}
	return ""
}

func (m *SAMPLEONE_StructName) GetCount() uint32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *SAMPLEONE_StructName) GetWeight() float64 {
	if m != nil && m.Weight != nil {
		return *m.Weight
	}
	return 0
}

type SAMPLEONE_ARRAY struct {
	SAMPLEONE        []*SAMPLEONE `protobuf:"bytes,1,rep,name=sAMPLEONE" json:"sAMPLEONE,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *SAMPLEONE_ARRAY) Reset()         { *m = SAMPLEONE_ARRAY{} }
func (m *SAMPLEONE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*SAMPLEONE_ARRAY) ProtoMessage()    {}

func (m *SAMPLEONE_ARRAY) GetSAMPLEONE() []*SAMPLEONE {
	if m != nil {
		return m.SAMPLEONE
	}
	return nil
}

func init() {
}
