// Code generated by protoc-gen-go.
// source: sampleone3.proto
// DO NOT EDIT!

/*
Package xlsx2pb is a generated protocol buffer package.

It is generated from these files:
	sampleone3.proto

It has these top-level messages:
	SAMPLEONE
	SAMPLEONE_ARRAY
*/
package xlsx2pb

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type SAMPLEONE struct {
	// Comment1
	SampleID uint64 `protobuf:"varint,2,opt" json:"SampleID,omitempty"`
	// Comment2
	Times int64 `protobuf:"varint,3,opt" json:"Times,omitempty"`
	// Comment3
	NameID     string                  `protobuf:"bytes,4,opt" json:"NameID,omitempty"`
	StructName []*SAMPLEONE_StructName `protobuf:"bytes,5,rep,name=structName" json:"structName,omitempty"`
}

func (m *SAMPLEONE) Reset()         { *m = SAMPLEONE{} }
func (m *SAMPLEONE) String() string { return proto.CompactTextString(m) }
func (*SAMPLEONE) ProtoMessage()    {}

func (m *SAMPLEONE) GetStructName() []*SAMPLEONE_StructName {
	if m != nil {
		return m.StructName
	}
	return nil
}

type SAMPLEONE_StructName struct {
	// Comment4
	RewardID string `protobuf:"bytes,1,opt" json:"RewardID,omitempty"`
	// Comment5
	Count uint32 `protobuf:"varint,2,opt" json:"Count,omitempty"`
	// Comment6
	Weight float64 `protobuf:"fixed64,3,opt" json:"Weight,omitempty"`
}

func (m *SAMPLEONE_StructName) Reset()         { *m = SAMPLEONE_StructName{} }
func (m *SAMPLEONE_StructName) String() string { return proto.CompactTextString(m) }
func (*SAMPLEONE_StructName) ProtoMessage()    {}

type SAMPLEONE_ARRAY struct {
	SAMPLEONE []*SAMPLEONE `protobuf:"bytes,1,rep,name=sAMPLEONE" json:"sAMPLEONE,omitempty"`
}

func (m *SAMPLEONE_ARRAY) Reset()         { *m = SAMPLEONE_ARRAY{} }
func (m *SAMPLEONE_ARRAY) String() string { return proto.CompactTextString(m) }
func (*SAMPLEONE_ARRAY) ProtoMessage()    {}

func (m *SAMPLEONE_ARRAY) GetSAMPLEONE() []*SAMPLEONE {
	if m != nil {
		return m.SAMPLEONE
	}
	return nil
}

func init() {
}
