[Config]
# Avoid using "~" or "$GOPATH" in path
# "." or ".." is acceptable but may cause problems
xlsx_path = "/Users/jiangyi/data/data/a3k/"

# Regular Expression of config files
config_reg_exp = "xlsx*.config"

xlsx_ext = ""

# use proto 2 or proto 3
use_proto3 = false

# proto
package_name = "ProtobufGen"    # proto package name
proto_path = "/Users/jiangyi/data/proto/"   # path to save all proto files
proto_ext = ".proto"

data_path = "/Users/jiangyi/data/data/" # path to save all binary files
data_ext = ".data"

cache_file = "/Users/jiangyi/data/cache/cache.json"

change_output_path = "/Users/jiangyi/data/output"  # path to save all changed files
change_log = "/Users/jiangyi/data/output/changelog.json"
